[accounts.gmail]
default = true
email = "jamal.siddique.work@gmail.com"
folder.alias.inbox = "INBOX"
folder.alias.sent = "[Gmail]/Sent Mail"
folder.alias.drafts = "[Gmail]/Drafts"
folder.alias.trash = "[Gmail]/Trash"
backend.type = "imap"
backend.host = "imap.gmail.com"
backend.port = 993
backend.login = "jamal.siddique.work@gmail.com"
backend.auth.type = "password"
backend.auth.raw = "JammiedodgerClapo1!"
message.send.backend.type = "smtp"
message.send.backend.host = "smtp.gmail.com"
message.send.backend.port = 465
message.send.backend.login = "jamal.siddique.work@gmail.com"
message.send.backend.auth.type = "password"
message.send.backend.auth.raw = "JammiedodgerClapo1!"

